application: socialvolunteernet
version: 1
api_version: 1
runtime: python27 
threadsafe: no

handlers:
- url: /browse
  script: socialvolunteernet/handler/browse_handler.py
- url: /org
  script: socialvolunteernet/handler/org_handler.py
- url: /volunteer
  script: socialvolunteernet/handler/vol_handler.py  
- url: /login
  script: socialvolunteernet/handler/auth_handler.py
- url: /
  static_dir: web