application: socialvolunteernet
version: 1
api_version: 1
runtime: python 

handlers:
- url: /
  script: socialvolunteer/handler/browse_handler.py
- url: /org
  script: socialvolunteer/handler/org_handler.py
- url: /volunteer
  script: socialvolunteer/handler/vol_handler.py  
- url: /login
  script: socialvolunteer/handler/auth_handler.py